services:
  - type: web
    name: anti5-0
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node backend/server.js
    healthCheckPath: /
    healthCheckTimeout: 60
    autoDeploy: false
    envVars:
      - key: NODE_ENV
        value: production
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
