services:
  - type: web
    name: anti5-0
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    healthCheckPath: /
    healthCheckTimeout: 60
    autoDeploy: false
    envVars:
      - key: NODE_ENV
        value: production
